### PR TITLE
Update Feed Default

### PR DESCRIPTION
**Pull request by michaelwehrley**
* Allow 10 items to be shown initially instead of 5
* This eliminates the feed bug for nearly all computer screens

[Finishes: #119336059]

### CODE REVIEW

**Comment by ericcf** [comment]
When you say "nearly all computer screens", which screens still have issues?

**Comment by michaelwehrley** [comment]
Good question.  So the problem came up when I removed sunnyside styling from marigold.  There must have been some padding or margin added by the styling b/c when I removed the styling scrolling was no longer necessary to see all feed items.  Therefore, one of my home feed specs failed b/c the window size was too large [1920 x 1080](https://github.com/NU-CBITS/marigold/commit/3bee30a198ff3912337227742619fd7493d47ba5) and the scroll failed to trigger the ajax call.  I then zoomed out on my own computer and noticed the same behavior.  So I figured that by doubling the size of the feed and given that my computer is larger than most (and I had to zoom out), that this would fix the problem for most computers.  I didn't think about the new retina screens so maybe that could be an issue.

**Comment by michaelwehrley** [comment]
related to: https://github.com/NU-CBITS/marigold/pull/173

**Comment by ericcf** [comment]
Ok, thanks!

**Pull request merged**
